export default [
  {
    "id": 3,
    "subject": "sub",
    "claim": "claim",
    "object": null,
    "qualifier": null,
    "aspect": null,
    "howKnown": null,
    "source": null,
    "effectiveDate": null,
    "confidence": null,
    "reviewRating": null,
    "userId": 1,
    "issuerId": "http://trustclaims.whatscookin.us/users/1",
    "issuerIdType": "URL",
    "createdAt": "2022-06-21T12:37:26.714Z",
    "lastUpdatedAt": "2022-06-21T12:37:26.714Z"
  },
  {
    "id": 7,
    "subject": "buildspace.so",
    "claim": "rated",
    "object": null,
    "qualifier": "developer training",
    "aspect": "impact:educational",
    "howKnown": "second_hand",
    "source": "Robert says buildspace is well done",
    "effectiveDate": "2022-06-27T04:54:22.513Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T04:58:23.498Z",
    "lastUpdatedAt": "2022-06-27T04:58:23.499Z"
  },
  {
    "id": 9,
    "subject": "https://github.com/sarthakvijayvergiya",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": "first_hand",
    "source": "Sarthak did top quality work for WhatsCookin from 2019-2021",
    "effectiveDate": "2022-06-27T05:15:53.445Z",
    "confidence": 1,
    "reviewRating": 5,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T05:17:24.968Z",
    "lastUpdatedAt": "2022-06-27T05:17:24.968Z"
  },
  {
    "id": 10,
    "subject": "https://github.com/sarthakvijayvergiya",
    "claim": "rated",
    "object": null,
    "qualifier": "stars on github",
    "aspect": "impact:work",
    "howKnown": "website",
    "source": "Looking at github",
    "effectiveDate": "2022-06-27T05:17:24.908Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T05:18:58.777Z",
    "lastUpdatedAt": "2022-06-27T05:18:58.777Z"
  },
  {
    "id": 12,
    "subject": "https://www.goodreads.com/book/show/40121378-atomic-habits",
    "claim": "rated",
    "object": null,
    "qualifier": "building/breaking habits; behavioral modification",
    "aspect": "impact:educational",
    "howKnown": "first_hand",
    "source": "read the book",
    "effectiveDate": "2022-06-27T05:20:04.852Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T06:00:35.434Z",
    "lastUpdatedAt": "2022-06-27T06:00:35.434Z"
  },
  {
    "id": 13,
    "subject": "https://www.goodreads.com/book/show/40121378-atomic-habits",
    "claim": "rated",
    "object": null,
    "qualifier": "ok read, a bit repetitive but accessible",
    "aspect": "quality:fun",
    "howKnown": null,
    "source": "read the book",
    "effectiveDate": "2022-06-27T06:00:35.362Z",
    "confidence": 1,
    "reviewRating": 2,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T06:01:14.533Z",
    "lastUpdatedAt": "2022-06-27T06:01:14.533Z"
  },
  {
    "id": 15,
    "subject": "A subject",
    "claim": "same_as",
    "object": "Some",
    "qualifier": null,
    "aspect": "impact:financial",
    "howKnown": "first_hand",
    "source": null,
    "effectiveDate": "2022-06-27T12:48:19.309Z",
    "confidence": 0.5,
    "reviewRating": 1,
    "userId": 4,
    "issuerId": "http://trustclaims.whatscookin.us/users/4",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T12:49:58.600Z",
    "lastUpdatedAt": "2022-06-27T12:49:58.600Z"
  },
  {
    "id": 16,
    "subject": "https://github.com/youngnishant",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": "first_hand",
    "source": null,
    "effectiveDate": "2022-06-27T15:10:15.884Z",
    "confidence": 0.9,
    "reviewRating": 4,
    "userId": 4,
    "issuerId": "http://trustclaims.whatscookin.us/users/4",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T15:11:57.850Z",
    "lastUpdatedAt": "2022-06-27T15:11:57.850Z"
  },
  {
    "id": 17,
    "subject": "https://www.upwork.com/freelancers/~015026aa111bf5eb6d",
    "claim": "same_as",
    "object": "https://github.com/pacodes",
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-06-27T15:11:58.024Z",
    "confidence": 1,
    "reviewRating": 1,
    "userId": 4,
    "issuerId": "http://trustclaims.whatscookin.us/users/4",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T15:14:21.383Z",
    "lastUpdatedAt": "2022-06-27T15:14:21.383Z"
  },
  {
    "id": 19,
    "subject": "https://rotarypeacecenternc.org/kibera-slum/",
    "claim": "rated",
    "object": "https://rotarypeacecenternc.org/kibera-slum/",
    "qualifier": "Kibera has so many NGO's in the area",
    "aspect": "impact:social",
    "howKnown": "website",
    "source": "https://dcid.sanford.duke.edu/when-kindness-kills-development/",
    "effectiveDate": "2022-06-28T18:54:53.610Z",
    "confidence": 0.9,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-28T19:23:02.975Z",
    "lastUpdatedAt": "2022-06-28T19:23:02.975Z"
  },
  {
    "id": 20,
    "subject": "https://www.yelp.com/biz/la-cuisine-cafe-san-francisco-4?hrid=JF1J3epEvjDVx-0q4tvfhw",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": null,
    "effectiveDate": "2022-06-29T15:49:23.693Z",
    "confidence": 1,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T15:58:43.011Z",
    "lastUpdatedAt": "2022-06-29T15:58:43.011Z"
  },
  {
    "id": 21,
    "subject": "https://www.yelp.com/biz/papalote-mexican-grill-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": null,
    "effectiveDate": "2022-06-29T15:58:43.006Z",
    "confidence": 1,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:03:59.778Z",
    "lastUpdatedAt": "2022-06-29T16:03:59.778Z"
  },
  {
    "id": 22,
    "subject": "https://www.yelp.com/biz/marufuku-ramen-san-francisco-5",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:03:59.775Z",
    "confidence": 0.99,
    "reviewRating": 4,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:07:21.574Z",
    "lastUpdatedAt": "2022-06-29T16:07:21.574Z"
  },
  {
    "id": 23,
    "subject": "https://www.yelp.com/biz/burma-superstar-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:07:21.548Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:11:32.328Z",
    "lastUpdatedAt": "2022-06-29T16:11:32.328Z"
  },
  {
    "id": 24,
    "subject": "https://www.yelp.com/biz/farmhouse-kitchen-thai-cuisine-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:11:32.273Z",
    "confidence": 0.91,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:13:21.563Z",
    "lastUpdatedAt": "2022-06-29T16:13:21.563Z"
  },
  {
    "id": 25,
    "subject": "https://www.yelp.com/biz/kitchen-story-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": null,
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:13:21.498Z",
    "confidence": 0.89,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:15:09.625Z",
    "lastUpdatedAt": "2022-06-29T16:15:09.625Z"
  },
  {
    "id": 26,
    "subject": "https://www.yelp.com/biz/sotto-mare-san-francisco-4",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:15:09.573Z",
    "confidence": 0.75,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:18:09.263Z",
    "lastUpdatedAt": "2022-06-29T16:18:09.263Z"
  },
  {
    "id": 28,
    "subject": "https://www.scientificamerican.com/article/deforestation-and-global-warming/",
    "claim": "rated",
    "object": "Climate Change",
    "qualifier": "Deforestation contributes to global warming",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.ucsusa.org/resources/tropical-deforestation-and-global-warming#:~:text=When%20forests%20are%20cut%20down,percent%20of%20global%20warming%20pollution.",
    "effectiveDate": "2022-06-29T20:21:56.423Z",
    "confidence": 0.7,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T20:29:19.194Z",
    "lastUpdatedAt": "2022-06-29T20:29:19.194Z"
  },
  {
    "id": 31,
    "subject": "https://www.getsmarter.com/blog/market-trends/the-future-of-blockchain-technology-in-2022/#:~:text=Blockchain%20has%20the%20potential%20to,the%20need%20for%20a%20middleman",
    "claim": "performed",
    "object": "Blockchain technology is the future ",
    "qualifier": "Blockchain technology is the futu ",
    "aspect": "quality:technical",
    "howKnown": "blockchain",
    "source": "https://www.europarl.europa.eu/RegData/etudes/IDAN/2017/581948/EPRS_IDA(2017)581948_EN.pdf",
    "effectiveDate": "2022-06-29T20:46:29.658Z",
    "confidence": 0.74,
    "reviewRating": 2,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T20:51:23.256Z",
    "lastUpdatedAt": "2022-06-29T20:51:23.256Z"
  },
  {
    "id": 32,
    "subject": "https://destinationscanner.com/is-kenya-a-third-world-country/",
    "claim": "rated",
    "object": "Kenya is a third world country",
    "qualifier": "Kenya is a third world country ",
    "aspect": "impact:financial",
    "howKnown": null,
    "source": "https://en.wikipedia.org/wiki/Economy_of_Kenya",
    "effectiveDate": "2022-06-29T20:51:23.330Z",
    "confidence": 0.85,
    "reviewRating": 2,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:05:22.958Z",
    "lastUpdatedAt": "2022-06-29T21:05:22.958Z"
  },
  {
    "id": 33,
    "subject": "https://www.thesandsatnomad.com/diani-beach-best-in-the-world/#:~:text=Voted%20as%20one%20of%20the,Ocean%20on%20Kenya's%20south%20coastline.",
    "claim": "rated",
    "object": "Diani is one of the best beaches in the Africa",
    "qualifier": "Diani is one of the best beaches in the Africa",
    "aspect": "impact:social",
    "howKnown": "website",
    "source": "https://www.brilliant-africa.com/kenya/diani-beach",
    "effectiveDate": "2022-06-29T21:05:23.048Z",
    "confidence": 0.89,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:09:50.969Z",
    "lastUpdatedAt": "2022-06-29T21:09:50.969Z"
  },
  {
    "id": 34,
    "subject": "https://en.wikipedia.org/wiki/Uganda",
    "claim": "rated",
    "object": "Uganda is a landlocked country ",
    "qualifier": "Uganda is a landlocked country because of its location ",
    "aspect": "impact:social",
    "howKnown": null,
    "source": "https://artsandculture.google.com/entity/uganda/m07tp2?hl=en",
    "effectiveDate": "2022-06-29T21:09:51.038Z",
    "confidence": 1,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:12:43.188Z",
    "lastUpdatedAt": "2022-06-29T21:12:43.188Z"
  },
  {
    "id": 35,
    "subject": "https://evaw-global-database.unwomen.org/en/countries/africa/kenya",
    "claim": "rated",
    "object": "Gender Based Violence in Kenya is rampant ",
    "qualifier": "Gender Based Violence in Kenya is rampant ",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.aljazeera.com/news/2021/9/21/hrw-kenya-response-surge-gender-based-violence-covid",
    "effectiveDate": "2022-06-29T21:12:43.248Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:18:35.806Z",
    "lastUpdatedAt": "2022-06-29T21:18:35.806Z"
  },
  {
    "id": 38,
    "subject": "https://www.yelp.com/biz/pearl-spa-and-sauna-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:asthetic",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:31:13.746Z",
    "confidence": 0.75,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T14:34:28.071Z",
    "lastUpdatedAt": "2022-06-30T14:34:28.071Z"
  },
  {
    "id": 40,
    "subject": "https://www.yelp.com/biz/kohshi-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:asthetic",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:36:54.849Z",
    "confidence": 0.86,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T14:42:39.933Z",
    "lastUpdatedAt": "2022-06-30T14:42:39.933Z"
  },
  {
    "id": 41,
    "subject": "https://www.yelp.com/biz/song-tea-and-ceramics-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:asthetic",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:42:39.945Z",
    "confidence": 0.75,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T14:44:13.950Z",
    "lastUpdatedAt": "2022-06-30T14:44:13.950Z"
  },
  {
    "id": 42,
    "subject": "https://www.yelp.com/biz/parada-22-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:44:13.939Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T14:46:17.553Z",
    "lastUpdatedAt": "2022-06-30T14:46:17.553Z"
  },
  {
    "id": 43,
    "subject": "https://www.yelp.com/biz/starbelly-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:46:17.565Z",
    "confidence": 0.7,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:02:05.869Z",
    "lastUpdatedAt": "2022-06-30T15:02:05.869Z"
  },
  {
    "id": 44,
    "subject": "https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T15:02:05.872Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:02:56.315Z",
    "lastUpdatedAt": "2022-06-30T15:02:56.315Z"
  },
  {
    "id": 46,
    "subject": "https://www.yelp.com/biz/nopa-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T15:04:24.948Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:06:14.255Z",
    "lastUpdatedAt": "2022-06-30T15:06:14.255Z"
  },
  {
    "id": 47,
    "subject": "https://www.yelp.com/biz/champa-garden-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T15:06:14.225Z",
    "confidence": 0.89,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:07:29.582Z",
    "lastUpdatedAt": "2022-06-30T15:07:29.582Z"
  },
  {
    "id": 48,
    "subject": "https://www.yelp.com/biz/la-note-berkeley-5?osq=restaurants",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T15:07:29.556Z",
    "confidence": 0.7,
    "reviewRating": 2,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:11:13.212Z",
    "lastUpdatedAt": "2022-06-30T15:11:13.212Z"
  },
  {
    "id": 49,
    "subject": "Test",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-06-30T20:46:15.242Z",
    "confidence": 0.5,
    "reviewRating": null,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T20:46:59.554Z",
    "lastUpdatedAt": "2022-06-30T20:46:59.554Z"
  },
  {
    "id": 50,
    "subject": "Test",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-06-30T20:46:59.692Z",
    "confidence": 1,
    "reviewRating": 2,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T20:47:17.928Z",
    "lastUpdatedAt": "2022-06-30T20:47:17.928Z"
  },
  {
    "id": 53,
    "subject": "https://www.thelivingurn.com/blogs/news/27-000-trees-are-used-each-day-just-to-make-toilet-paper",
    "claim": "rated",
    "object": " Around 27,000 trees are cut down each day ",
    "qualifier": "The world has over 3.04 trillion trees in the world. However, 27,000 of them are cut down daily to make toilet paper. This translates to about 9.8 million trees annually. One single recycled edition of the New York Times newspaper could save 75,000 tree",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.mirror.co.uk/news/world-news/27000-trees-cut-down-every-20858878",
    "effectiveDate": "2022-07-01T08:31:03.576Z",
    "confidence": 0.57,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:40:18.098Z",
    "lastUpdatedAt": "2022-07-01T08:40:18.098Z"
  },
  {
    "id": 54,
    "subject": "https://www.wwf.org.au/news/blogs/plastic-in-our-oceans-is-killing-marine-mammals",
    "claim": "rated",
    "object": " marine mammals are at risk of choking on plastic",
    "qualifier": " marine mammals are at risk of accidental deaths, such as getting caught in fishing nets. Plastic bags and other plastic garbage that ends up in the ocean ",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://australian.museum/blog/museullaneous/plastic-in-our-oceans-is-killing-marine-mammals/",
    "effectiveDate": "2022-07-01T08:40:22.108Z",
    "confidence": 0.74,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:46:03.789Z",
    "lastUpdatedAt": "2022-07-01T08:46:03.789Z"
  },
  {
    "id": 56,
    "subject": "https://www.decadeonrestoration.org/stories/benefits-fungi-environment-and-humans#:~:text=Nutrient%20Cycling,-Fungi%20have%20the&text=Some%20fungi%20are%20decomposers%20which,for%20plant%20development%20and%20productivity.",
    "claim": "rated",
    "object": "Fungi play a highly vital role in the environment",
    "qualifier": "Fungi play a protective role in the environment. From digesting minerals out of rock formations to consuming fossil fuel spills, and even de-radiating the environment",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.decadeonrestoration.org/",
    "effectiveDate": "2022-07-01T08:55:16.624Z",
    "confidence": 0.75,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:58:06.938Z",
    "lastUpdatedAt": "2022-07-01T08:58:06.938Z"
  },
  {
    "id": 57,
    "subject": "https://www.bbc.com/news/magazine-29281253",
    "claim": "rated",
    "object": " Ants weigh more than humans",
    "qualifier": "The combined weight of ants on the planet is higher than all human beings. The world has over 7 billion people, and 100 trillion ants.",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.bbc.com/news",
    "effectiveDate": "2022-07-01T08:58:08.893Z",
    "confidence": 0.74,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:00:42.548Z",
    "lastUpdatedAt": "2022-07-01T09:00:42.548Z"
  },
  {
    "id": 58,
    "subject": "https://www.recycleacrossamerica.org/recycling-facts#:~:text=Every%20three%20months%2C%20Americans%20throw,a%20TV%20for%20three%20hours.",
    "claim": "rated",
    "object": "Americans throw enough aluminum in the landfills to build our nation’s entire commercial air fleet.",
    "qualifier": "Recycling one aluminum can save enough energy to run a TV for three hours. During the time it takes you to read this sentence, 50,000 12-ounce aluminum cans are made.",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.recycleacrossamerica.org/",
    "effectiveDate": "2022-07-01T09:00:44.530Z",
    "confidence": 0.77,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:04:00.321Z",
    "lastUpdatedAt": "2022-07-01T09:04:00.321Z"
  },
  {
    "id": 59,
    "subject": "https://sciencing.com/earth-friendly-food-storage-containers-2018.html",
    "claim": "rated",
    "object": " A glass bottle can take up to 1 million years to decompose.",
    "qualifier": "Glass takes a very, very long time to break down. It can take a glass bottle more than a million years to decompose in the environment, possibly even more if it’s in a landfill. This means that glass manufactured and used 5000 years ago may still be present in the environment. Because its life cycle is so long, and because glass doesn’t leach any chemicals, it’s better to repurpose and reuse it over and over again before recycling it. ",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://sciencing.com/",
    "effectiveDate": "2022-07-01T09:04:02.260Z",
    "confidence": 0.71,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:12:04.838Z",
    "lastUpdatedAt": "2022-07-01T09:12:04.838Z"
  },
  {
    "id": 60,
    "subject": "https://education.nationalgeographic.org/resource/great-pacific-garbage-patch",
    "claim": "rated",
    "object": "  There is a giant floating patch of garbage ",
    "qualifier": "The Great Pacific Garbage Patch is a twisting and turning vortex composed of trash and waste. It is twice the size of continental America and contains about 100 million tons of garbage, it stretches from the West Coast of North America to Japan along the Pacific Ocean. ",
    "aspect": "impact:educational",
    "howKnown": null,
    "source": "https://www.nationalgeographic.org/",
    "effectiveDate": "2022-07-01T09:12:06.795Z",
    "confidence": 0.76,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:16:19.955Z",
    "lastUpdatedAt": "2022-07-01T09:16:19.955Z"
  },
  {
    "id": 61,
    "subject": "https://www.nytimes.com/2010/12/21/science/21qna.html#:~:text=A.,at%20five%20to%20seven%20times.",
    "claim": "rated",
    "object": " Paper from trees can be recycled 6 times. ",
    "qualifier": "Paper comes from trees and can be recycled a maximum of six times, after which, its fibers become too weak to hold together",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nytimes.com/",
    "effectiveDate": "2022-07-01T09:16:21.902Z",
    "confidence": 0.81,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:22:05.407Z",
    "lastUpdatedAt": "2022-07-01T09:22:05.407Z"
  },
  {
    "id": 63,
    "subject": "https://worldpopulationreview.com/continents/africa-population",
    "claim": "rated",
    "object": "1.2 Billion people live in Africa",
    "qualifier": "That’s 16% of the world’s population.",
    "aspect": "impact:social",
    "howKnown": "website",
    "source": "https://worldpopulationreview.com/",
    "effectiveDate": "2022-07-01T09:25:57.114Z",
    "confidence": 0.71,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:49:16.128Z",
    "lastUpdatedAt": "2022-07-01T09:49:16.128Z"
  },
  {
    "id": 65,
    "subject": "https://www.alphatrad.com/news/afrikan-languages",
    "claim": "rated",
    "object": "Swahili is the most spoken language in Africa.",
    "qualifier": "The Bantu language Swahili is spoken by about 150 million people in Central and Southern Africa in the Great Lakes region. The origin of the word Swahili comes from Arabic and means coast. For the inhabitants along the coast from Somalia to Mozambique, Swahili is the mother tongue.",
    "aspect": "impact:social",
    "howKnown": "website",
    "source": "https://www.alphatrad.com/",
    "effectiveDate": "2022-07-01T09:53:54.969Z",
    "confidence": 0.83,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:59:11.244Z",
    "lastUpdatedAt": "2022-07-01T09:59:11.244Z"
  },
  {
    "id": 66,
    "subject": "https://www.statista.com/statistics/1051514/africa-share-diamond-production-worldwide/",
    "claim": "rated",
    "object": "Most of the world’s diamonds come from Africa",
    "qualifier": " As much as 95 percent of the world’s diamonds and 50 percent of the world’s gold comes from Africa",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.statista.com/",
    "effectiveDate": "2022-07-01T09:59:13.184Z",
    "confidence": 0.79,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:06:47.202Z",
    "lastUpdatedAt": "2022-07-01T10:06:47.202Z"
  },
  {
    "id": 67,
    "subject": "https://education.nationalgeographic.org/resource/Continent",
    "claim": "rated",
    "object": "Africa is the second largest continent ",
    "qualifier": "Africa, the second-largest continent, covers an area more than three times that of the United States. From north to south, Africa stretches about 8,000 kilometers (5,000 miles). It is connected to Asia by the Isthmus of Suez in Egypt",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nationalgeographic.org/society/",
    "effectiveDate": "2022-07-01T10:06:49.142Z",
    "confidence": 0.69,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:10:34.410Z",
    "lastUpdatedAt": "2022-07-01T10:10:34.411Z"
  },
  {
    "id": 68,
    "subject": "https://africafreak.com/most-dangerous-animals-in-africa",
    "claim": "rated",
    "object": "Hippos causes more death than any other animal in Africa ",
    "qualifier": "Hippos are the most dangerous mammals in Africa, responsible for around 500 human casualties every year.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://africafreak.com/",
    "effectiveDate": "2022-07-01T10:10:36.317Z",
    "confidence": 0.83,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:15:36.687Z",
    "lastUpdatedAt": "2022-07-01T10:15:36.687Z"
  },
  {
    "id": 69,
    "subject": "https://intro.africa/story/the-nubian-pyramids-of-sudan/#:~:text=Sudan%20has%20more%20ancient%20pyramids%20than%20Egypt&text=There%20are%20around%202000%20Kushite,compared%20with%20200%20Egyptian%20pyramids.",
    "claim": "rated",
    "object": "SUDAN HAS MORE PYRAMIDS THAN EGYPT",
    "qualifier": "The country of Egypt may be famous for its pyramids but many people don’t realise that the country of Sudan, in Africa, has a total of 223 pyramids. This is twice the amount of pyramids that Egypt has! These forgotten pyramids are the Meroe Pyramids; these once made up the capital of the Kingdom of Kush, ruled by the Nubian kings.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://intro.africa/",
    "effectiveDate": "2022-07-01T10:15:38.602Z",
    "confidence": 0.86,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:19:29.639Z",
    "lastUpdatedAt": "2022-07-01T10:19:29.639Z"
  },
  {
    "id": 71,
    "subject": "https://eloquentjavascript.net/",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:academic",
    "howKnown": "website",
    "source": null,
    "effectiveDate": "2022-07-01T10:14:18.979Z",
    "confidence": 1,
    "reviewRating": 5,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:23:54.667Z",
    "lastUpdatedAt": "2022-07-01T10:23:54.667Z"
  },
  {
    "id": 72,
    "subject": "https://www.dvv-international.de/en/adult-education-and-development/editions/aed-802013-post-2015/articles/literacy-in-africa-its-in-our-own-hands",
    "claim": "rated",
    "object": " ILLITERACY IS AS HIGH AS 40% ACROSS THE CONTINENT",
    "qualifier": "Although Africa holds many different resources it is a continent where many of the countries have vast numbers of their populations living in poverty. This has led to 40% of adults in Africa being illiterate. The worst affected areas, with shocking illiteracy over 50% are in Ethiopia, Chad, Gambia, Sierra Leone, Senegal, Niger, Benin and Burkina Faso.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.dvv-international.de/en/",
    "effectiveDate": "2022-07-01T10:22:27.689Z",
    "confidence": 0.83,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:26:55.727Z",
    "lastUpdatedAt": "2022-07-01T10:26:55.727Z"
  },
  {
    "id": 73,
    "subject": "https://www.bbc.com/news/av/world-africa-45979768",
    "claim": "rated",
    "object": "NIGERIA HAS THE HIGHEST NUMBER OF TWINS BORN IN THE WORLD",
    "qualifier": "One of Africa’s largest countries, Nigeria, has been nicknamed “The Land of Twins” by the BBC because it has the highest rate of twin births in the world. Numbers show that twin birth rates in West Africa are actually four times higher here than anywhere else in the world and the centre of it all takes place in a sleepy little town in Nigeria called Igbo-Ora where the last recorded figures revealed an average of 50 sets of twins in every 1,000 births.",
    "aspect": "impact:educational",
    "howKnown": "verified_website",
    "source": "https://www.bbc.com/news",
    "effectiveDate": "2022-07-01T10:26:57.639Z",
    "confidence": 0.8,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:29:31.074Z",
    "lastUpdatedAt": "2022-07-01T10:29:31.074Z"
  },
  {
    "id": 74,
    "subject": "https://yaleclimateconnections.org/2018/07/the-sahara-desert-is-getting-bigger/",
    "claim": "rated",
    "object": "The Sahara Desert is getting bigger",
    "qualifier": "the Sahara is that it is actually growing in size as it’s been expanding in the southern regions at a rate of half a mile per month which equates to six miles per year!",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://yaleclimateconnections.org/",
    "effectiveDate": "2022-07-01T10:29:32.986Z",
    "confidence": 0.69,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:34:12.428Z",
    "lastUpdatedAt": "2022-07-01T10:34:12.428Z"
  },
  {
    "id": 75,
    "subject": "https://www.harpercollins.com/products/why-has-nobody-told-me-this-before-julie-smith?variant=39395371647010",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:academic",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-07-01T10:23:54.802Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:37:37.277Z",
    "lastUpdatedAt": "2022-07-01T10:37:37.277Z"
  },
  {
    "id": 76,
    "subject": "https://www.barnesandnoble.com/w/almond-won-pyung-sohn/1132004513",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:fun",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-07-01T10:37:37.412Z",
    "confidence": 1,
    "reviewRating": 3,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:41:06.918Z",
    "lastUpdatedAt": "2022-07-01T10:41:06.918Z"
  },
  {
    "id": 77,
    "subject": "https://edviesturs.com/products/no-shortcuts-to-the-top",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:fun",
    "howKnown": "first_hand",
    "source": null,
    "effectiveDate": "2022-07-01T10:41:07.056Z",
    "confidence": 1,
    "reviewRating": 5,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:47:13.685Z",
    "lastUpdatedAt": "2022-07-01T10:47:13.685Z"
  },
  {
    "id": 81,
    "subject": "https://www.smithsonianmag.com/science-nature/african-grey-parrots-have-the-reasoning-skills-of-3-year-olds-15955221/",
    "claim": "rated",
    "object": "Parrots have the power of reason.",
    "qualifier": "In addition to humans and chimps, the African grey parrot has been found to be able to reason—approximately at the level of a three-year-old kid, according to Smithsonian magazine. In an experiment, the parrots were presented with a pair of closed canisters, and shown that there was food inside one of them. When the parrots were given the chance to choose between canisters, they consistently selected the one with food.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.livescience.com/14708-parrots-logical-thinking.html#:~:text=Parrots%20are%20capable%20of%20logical,bit%20of%20food%20was%20hidden.&text=The%20task%20is%20one%20that,of%20reasoning%20are%20great%20apes.",
    "effectiveDate": "2022-07-01T10:56:13.079Z",
    "confidence": 0.84,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:59:24.223Z",
    "lastUpdatedAt": "2022-07-01T10:59:24.223Z"
  },
  {
    "id": 82,
    "subject": "https://torontopubliclibrary.typepad.com/north-york-central-blog/2015/03/sea-otters-holding-hands.html#:~:text=To%20prevent%20themselves%20from%20floating,drifting%20away%20from%20the%20group.",
    "claim": "rated",
    "object": "Sea otters hold hands while they sleep.",
    "qualifier": "This ridiculously cute behavior is an effort to avoid floating away from their partner during sleep. Sometimes they hold hands in groups, producing a \"raft.\"",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.dailymail.co.uk/news/article-2421731/Otterly-adorable-Dozy-otters-hold-hands-taking-nap-dont-drift-apart-sleep.html",
    "effectiveDate": "2022-07-01T10:59:25.339Z",
    "confidence": 0.69,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T11:04:35.689Z",
    "lastUpdatedAt": "2022-07-01T11:04:35.689Z"
  },
  {
    "id": 84,
    "subject": "https://www.abc.net.au/perth/programs/wa-afternoons/black-sapote/9408386",
    "claim": "rated",
    "object": "There is a fruit that tastes like chocolate pudding.",
    "qualifier": "Black sapote has another irresistible name: the chocolate pudding fruit. According to Good Morning America, the fruit—native to Central and South America—tastes like sweet custard with a hint of chocolate. When it's fully ripe, the flavor (and consistency) has been described as a dead ringer for chocolate pudding.",
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "https://www.abc.net.au/perth",
    "effectiveDate": "2022-07-01T11:07:08.684Z",
    "confidence": 0.71,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T11:13:28.128Z",
    "lastUpdatedAt": "2022-07-01T11:13:28.128Z"
  },
  {
    "id": 85,
    "subject": "https://pubmed.ncbi.nlm.nih.gov/20329590/#:~:text=Abstract,integrity%20and%20ability%20to%20perform.",
    "claim": "rated",
    "object": "The majority of your brain is fat.",
    "qualifier": "Abstract. The human brain is nearly 60 percent fat. We've learned in recent years that fatty acids are among the most crucial molecules that determine your brain's integrity and ability to perform.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.ncbi.nlm.nih.gov/",
    "effectiveDate": "2022-07-01T11:13:28.262Z",
    "confidence": 0.65,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T11:16:46.014Z",
    "lastUpdatedAt": "2022-07-01T11:16:46.014Z"
  },
  {
    "id": 86,
    "subject": "https://www.scienceabc.com/nature/how-do-butterflies-taste-and-eat-their-food.html",
    "claim": "rated",
    "object": "Butterflies taste with their feet.",
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "https://www.scienceabc.com/",
    "effectiveDate": "2022-07-01T11:16:46.425Z",
    "confidence": 0.58,
    "reviewRating": 4,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T13:41:46.452Z",
    "lastUpdatedAt": "2022-07-01T13:41:46.452Z"
  },
  {
    "id": 87,
    "subject": "https://www.azpetvet.com/can-certain-snails-really-sleep-for-3-years/#:~:text=Snails%20need%20moisture%20to%20survive,helping%20to%20escape%20warm%20climates.",
    "claim": "rated",
    "object": "A snail can sleep for three years.",
    "qualifier": "Snails need moisture to survive; so if the weather is not cooperating, they can actually sleep up to three years. It has been reported that depending on geography, snails can shift into hibernation (which occurs in the winter), or estivation (also known as ‘summer sleep’), helping to escape warm climates",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.azpetvet.com/",
    "effectiveDate": "2022-07-01T13:41:46.531Z",
    "confidence": 0.73,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T13:46:44.356Z",
    "lastUpdatedAt": "2022-07-01T13:46:44.356Z"
  },
  {
    "id": 88,
    "subject": "https://www.windowtonews.com/news.php?id=239388&cat_id=31&p=3&search=",
    "claim": "rated",
    "object": "A shrimp's heart is in its head.",
    "qualifier": "A shrimp's heart is located on its head. But if we will base it on the exact anatomy of a shrimp, its heart is located on its thorax just after the head, but both the head and the thorax are covered with a single exoskeleton only, that is why the shrimp's thorax can be mistaken as still part of the shrimps head",
    "aspect": "quality:academic",
    "howKnown": "website",
    "source": "https://www.windowtonews.com/",
    "effectiveDate": "2022-07-01T13:46:44.401Z",
    "confidence": 0.78,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:00:53.664Z",
    "lastUpdatedAt": "2022-07-01T14:00:53.664Z"
  },
  {
    "id": 89,
    "subject": "https://www.cdc.gov/mosquitoes/about/what-is-a-mosquito.html#:~:text=Only%20female%20mosquitoes%20bite%20people,bite%20infected%20people%20and%20animals.",
    "claim": "rated",
    "object": "Only female mosquitoes bite.",
    "qualifier": "Only female mosquitoes bite people and animals to get a blood meal. Female mosquitoes need a blood meal to produce eggs.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.cdc.gov/",
    "effectiveDate": "2022-07-01T14:00:53.739Z",
    "confidence": 0.74,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:06:24.086Z",
    "lastUpdatedAt": "2022-07-01T14:06:24.086Z"
  },
  {
    "id": 90,
    "subject": "https://oceanservice.noaa.gov/facts/jellyfish.html#:~:text=Only%20about%20five%20percent%20of,are%20about%2095%20percent%20water.",
    "claim": "rated",
    "object": "The jellyfish is 95% water.",
    "qualifier": "Only about five percent of the body of a jellyfish is solid matter; the rest is water. A jellyfish Fascinating, elegant, and mysterious to watch in the water, take a jellyfish out of the water, and it becomes a much less fascinating blob. This is because jellyfish are about 95 percent water.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://oceanservice.noaa.gov/",
    "effectiveDate": "2022-07-01T14:06:24.227Z",
    "confidence": 0.67,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:08:47.716Z",
    "lastUpdatedAt": "2022-07-01T14:08:47.716Z"
  },
  {
    "id": 91,
    "subject": "https://animals.howstuffworks.com/mammals/dolphins-sleep-half-brain-at-time.htm#:~:text=You've%20heard%20of%20%22sleeping,the%20opposite%20eye%20is%20closed.",
    "claim": "rated",
    "object": "Dolphins sleep with one eye open.",
    "qualifier": "You've heard of \"sleeping with one eye open.\" That's how dolphins catch their Zzzs — one side of their brain stays awake and the opposite eye stays open to watch for danger and rise to the surface to breathe. Meanwhile, the other half of brain sleeps and the opposite eye is closed",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.howstuffworks.com/",
    "effectiveDate": "2022-07-01T14:08:47.948Z",
    "confidence": 0.74,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:10:58.456Z",
    "lastUpdatedAt": "2022-07-01T14:10:58.456Z"
  },
  {
    "id": 2,
    "subject": "sub",
    "claim": "claim",
    "object": "obj",
    "qualifier": "qualifier",
    "aspect": "aspect",
    "howKnown": "well",
    "source": "www.someurl.com",
    "effectiveDate": "2022-06-03T18:06:02.608Z",
    "confidence": 1,
    "reviewRating": 2,
    "userId": 1,
    "issuerId": "http://trustclaims.whatscookin.us/users/1",
    "issuerIdType": "URL",
    "createdAt": "2022-06-21T12:37:10.610Z",
    "lastUpdatedAt": "2022-06-21T12:37:10.610Z"
  },
  {
    "id": 6,
    "subject": "He",
    "claim": "Test",
    "object": null,
    "qualifier": null,
    "aspect": null,
    "howKnown": null,
    "source": null,
    "effectiveDate": "2012-10-18T15:15:47.000Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-22T15:16:35.282Z",
    "lastUpdatedAt": "2022-06-22T15:16:35.282Z"
  },
  {
    "id": 5,
    "subject": "A ",
    "claim": "b",
    "object": "c",
    "qualifier": "d",
    "aspect": "e",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-06-21T19:52:20.156Z",
    "confidence": 1,
    "reviewRating": 2,
    "userId": 2,
    "issuerId": "http://trustclaims.whatscookin.us/users/2",
    "issuerIdType": "URL",
    "createdAt": "2022-06-21T19:52:33.671Z",
    "lastUpdatedAt": "2022-06-21T19:52:33.671Z"
  },
  {
    "id": 8,
    "subject": "https://www.upwork.com/freelancers/~01153e763895da5617",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:technical",
    "howKnown": "website",
    "source": "upwork rating",
    "effectiveDate": "2022-06-27T05:07:46.072Z",
    "confidence": 1,
    "reviewRating": 5,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T05:15:53.481Z",
    "lastUpdatedAt": "2022-06-27T05:15:53.481Z"
  },
  {
    "id": 11,
    "subject": "https://github.com/sarthakvijayvergiya",
    "claim": "same_as",
    "object": "https://twitter.com/sarthakvijayver",
    "qualifier": null,
    "aspect": null,
    "howKnown": "first_hand",
    "source": null,
    "effectiveDate": "2022-06-27T05:18:58.717Z",
    "confidence": 1,
    "reviewRating": 1,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T05:20:04.911Z",
    "lastUpdatedAt": "2022-06-27T05:20:04.911Z"
  },
  {
    "id": 14,
    "subject": "A subject",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "impact:work",
    "howKnown": "second_hand",
    "source": "asf",
    "effectiveDate": "2022-06-27T12:47:48.696Z",
    "confidence": 2e-323,
    "reviewRating": 1,
    "userId": 4,
    "issuerId": "http://trustclaims.whatscookin.us/users/4",
    "issuerIdType": "URL",
    "createdAt": "2022-06-27T12:48:19.105Z",
    "lastUpdatedAt": "2022-06-27T12:48:19.105Z"
  },
  {
    "id": 18,
    "subject": "https://journals.openedition.org/eastafrica/521?lang=en#:~:text=Given%20that%20the%20surface%20area,250%2C000%20inhabitants%20per%20km2).",
    "claim": "rated",
    "object": "https://worldpopulationreview.com/countries/kenya-population",
    "qualifier": "Kibera is overpopulated",
    "aspect": "impact:social",
    "howKnown": "website",
    "source": "https://www.researchgate.net/figure/Kiberas-population-growth-Data-source-An-average-of-Kenya-Bureau-of-Statistics_fig3_50392060",
    "effectiveDate": "2022-06-28T18:21:37.285Z",
    "confidence": 0.99,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-28T18:54:53.403Z",
    "lastUpdatedAt": "2022-06-28T18:54:53.403Z"
  },
  {
    "id": 27,
    "subject": "https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-29T16:18:09.190Z",
    "confidence": 0.9,
    "reviewRating": 4,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T16:47:30.315Z",
    "lastUpdatedAt": "2022-06-29T16:47:30.315Z"
  },
  {
    "id": 29,
    "subject": "https://www.minv.sk/?survey&okruh=2&tema=11#:~:text=Corruption%20is%20one%20of%20the,political%2C%20economic%20and%20social%20system.",
    "claim": "related_to",
    "object": "Impact of corruption in a society ",
    "qualifier": "Corruption is a social problem",
    "aspect": "impact:social",
    "howKnown": "verified_website",
    "source": "https://www.quora.com/Why-is-corruption-a-social-problem",
    "effectiveDate": "2022-06-29T20:29:19.292Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T20:37:46.119Z",
    "lastUpdatedAt": "2022-06-29T20:37:46.119Z"
  },
  {
    "id": 30,
    "subject": "https://www.news24.com/citypress/news/digital-and-tech-work-offer-opportunities-for-unemployed-youth-20201104",
    "claim": "rated",
    "object": "Technology is offering jobs to youth ",
    "qualifier": "Technology is offering opportunities to unemployed youths",
    "aspect": "impact:work",
    "howKnown": "website",
    "source": "https://blogs.worldbank.org/voices/digital-skills-great-potential-economic-opportunities-youth",
    "effectiveDate": "2022-06-29T20:37:46.232Z",
    "confidence": 0.8,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T20:46:29.554Z",
    "lastUpdatedAt": "2022-06-29T20:46:29.554Z"
  },
  {
    "id": 36,
    "subject": "https://www.thebalance.com/inflation-impact-on-economy-3306102#:~:text=Inflation%20raises%20prices%2C%20lowering%20your,on%20loans%20increase%20during%20inflation.",
    "claim": "related_to",
    "object": "inflations affecting the purchasing power ",
    "qualifier": "inflations affecting the purchasing power ",
    "aspect": "impact:financial",
    "howKnown": "website",
    "source": "https://www.economicsobservatory.com/how-does-inflation-affect-the-economy-when-interest-rates-are-near-zero",
    "effectiveDate": "2022-06-29T21:18:35.903Z",
    "confidence": 0.56,
    "reviewRating": 2,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:39:03.757Z",
    "lastUpdatedAt": "2022-06-29T21:39:03.757Z"
  },
  {
    "id": 37,
    "subject": "https://www.usgs.gov/faqs/when-did-dinosaurs-become-extinct#:~:text=Dinosaurs%20went%20extinct%20about%2065,for%20about%20165%20million%20years.",
    "claim": "rated",
    "object": "Dinosaurs are extinct ",
    "qualifier": "Dinosaurs are extinct ",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nationalgeographic.com/science/article/dinosaur-extinction",
    "effectiveDate": "2022-06-29T21:39:03.831Z",
    "confidence": 0.82,
    "reviewRating": 3,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-06-29T21:43:01.254Z",
    "lastUpdatedAt": "2022-06-29T21:43:01.254Z"
  },
  {
    "id": 39,
    "subject": "https://www.yelp.com/biz/siam-orchid-traditional-thai-massage-san-francisco-2",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:asthetic",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T14:34:28.092Z",
    "confidence": 0.85,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T14:36:54.813Z",
    "lastUpdatedAt": "2022-06-30T14:36:54.813Z"
  },
  {
    "id": 45,
    "subject": "https://www.yelp.com/biz/surisan-san-francisco",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "Yelp",
    "effectiveDate": "2022-06-30T15:02:56.285Z",
    "confidence": 0.75,
    "reviewRating": 3,
    "userId": 9,
    "issuerId": "http://trustclaims.whatscookin.us/users/9",
    "issuerIdType": "URL",
    "createdAt": "2022-06-30T15:04:24.799Z",
    "lastUpdatedAt": "2022-06-30T15:04:24.799Z"
  },
  {
    "id": 51,
    "subject": "https://host-students.com/the-importance-of-planting-trees/",
    "claim": "helped",
    "object": "Planting trees impacts our life ",
    "qualifier": "Planting trees impacts our life ",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.worldlandtrust.org/",
    "effectiveDate": "2022-07-01T08:04:03.685Z",
    "confidence": 0.99,
    "reviewRating": 4,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:22:39.642Z",
    "lastUpdatedAt": "2022-07-01T08:22:39.642Z"
  },
  {
    "id": 52,
    "subject": "https://www.usgs.gov/special-topics/water-science-school/science/how-much-water-there-earth",
    "claim": "rated",
    "object": "About 71% of the earth is water. The oceans hold approximately 96.5% of this water and the ice caps hold about 2%. The remaining water exists in rivers, ponds, glaciers, ice caps, lakes, as water vapor and our taps, among other water bodies. Only 1% of the earth’s water is safe for human consumption.",
    "qualifier": "About 71% of the earth is water. The oceans hold approximately 96.5% of this water and the ice caps hold about 2%. The remaining water exists in rivers, ponds, glaciers, ice caps, lakes, as water vapor and our taps, among other water bodies. Only 1% of the earth’s water is safe for human consumption.",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.usgs.gov/special-topics/water-science-school",
    "effectiveDate": "2022-07-01T08:22:42.723Z",
    "confidence": 0.69,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:31:00.102Z",
    "lastUpdatedAt": "2022-07-01T08:31:00.102Z"
  },
  {
    "id": 55,
    "subject": "https://www.earthday.org/fact-sheet-how-much-disposable-plastic-we-use/",
    "claim": "rated",
    "object": "Plastic pollution impact on the environment ",
    "qualifier": "The amount of single-use plastics used globally has tripled since the start of the pandemic, with takeout orders driving the increase",
    "aspect": "impact:climate",
    "howKnown": "website",
    "source": "https://www.statista.com/statistics/1134796/plastic-production-by-industrial-sector-worldwide/",
    "effectiveDate": "2022-07-01T08:46:05.794Z",
    "confidence": 0.73,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T08:55:14.637Z",
    "lastUpdatedAt": "2022-07-01T08:55:14.637Z"
  },
  {
    "id": 78,
    "subject": "https://en.wikipedia.org/wiki/Mpemba_effect#:~:text=The%20Mpemba%20effect%20is%20the,required%20to%20produce%20the%20effect.",
    "claim": "rated",
    "object": "Hot water freezes faster than cold water.",
    "qualifier": "A number of explanations have been suggested for \"the Mpemba effect,\" including one that posits warm containers conduct heat more efficiently, and another that suggests warm water evaporates faster.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://en.wikipedia.org/",
    "effectiveDate": "2022-07-01T10:34:14.333Z",
    "confidence": 0.75,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:50:42.741Z",
    "lastUpdatedAt": "2022-07-01T10:50:42.741Z"
  },
  {
    "id": 93,
    "subject": "https://gizmodo.com/why-honey-is-the-only-food-that-doesnt-go-bad-1225915466",
    "claim": "rated",
    "object": "The only food that does not spoil: honey.",
    "qualifier": "HoneyHoney is the only food that actually lasts forever and never spoils. We can thank nature for the whole process of making and procuring honey. It is made using the nectar of the flowers which mixes with the enzymes extracted by the bees",
    "aspect": "quality:taste",
    "howKnown": "website",
    "source": "https://gizmodo.com/",
    "effectiveDate": "2022-07-01T14:13:18.479Z",
    "confidence": 0.63,
    "reviewRating": 4,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:16:36.752Z",
    "lastUpdatedAt": "2022-07-01T14:16:36.752Z"
  },
  {
    "id": 96,
    "subject": "Another time",
    "claim": "same_as",
    "object": null,
    "qualifier": null,
    "aspect": "quality:fun",
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-07-07T20:42:29.095Z",
    "confidence": 1,
    "reviewRating": null,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-07T20:43:06.858Z",
    "lastUpdatedAt": "2022-07-07T20:43:06.858Z"
  },
  {
    "id": 4,
    "subject": "A sub",
    "claim": "A claim",
    "object": "An object",
    "qualifier": "A qualifier",
    "aspect": null,
    "howKnown": null,
    "source": null,
    "effectiveDate": "2022-06-21T19:38:16.976Z",
    "confidence": 1,
    "reviewRating": 5,
    "userId": 2,
    "issuerId": "http://trustclaims.whatscookin.us/users/2",
    "issuerIdType": "URL",
    "createdAt": "2022-06-21T19:43:20.029Z",
    "lastUpdatedAt": "2022-06-21T19:43:20.029Z"
  },
  {
    "id": 62,
    "subject": "https://www.treesatlanta.org/news/the-oldest-tree-in-the-world/#:~:text=The%20Great%20Basin%20Bristlecone%20Pine,harsh%20conditions%20it%20lives%20in.",
    "claim": "rated",
    "object": "The world’s oldest trees are 4,600 year old Bristlecone pines in the USA.",
    "qualifier": "The Great Basin Bristlecone Pine (Pinus Longaeva) has been deemed the oldest tree in existence, reaching an age of over 5,000 years old. The Bristlecone pines’ success in living a long life can be attributed to the harsh conditions it lives in. Very cold temperatures associated with high winds, in addition to a slow growth rate, create dense wood, meaning some years they grow so slowly, they don’t add a ring of growth",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.treesatlanta.org/",
    "effectiveDate": "2022-07-01T09:24:08.145Z",
    "confidence": 0.71,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:25:55.190Z",
    "lastUpdatedAt": "2022-07-01T09:25:55.190Z"
  },
  {
    "id": 80,
    "subject": "https://www.tepapa.govt.nz/discover-collections/read-watch-play/science/anatomy-colossal-squid/eyes-colossal-squid#:~:text=The%20colossal%20squid%20has%20the,size%20of%20a%20soccer%20ball.",
    "claim": "rated",
    "object": "Giant squids have the largest eyes of any animal on Earth.",
    "qualifier": "If you're not sufficiently scared of giant squids, consider that their eyes are 11 inches across. That makes them the largest known eyes in the animal kingdom.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nbcnews.com/id/wbna24386003#.Xe_oiJNKhBw",
    "effectiveDate": "2022-07-01T10:53:11.919Z",
    "confidence": 0.82,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:56:12.972Z",
    "lastUpdatedAt": "2022-07-01T10:56:12.972Z"
  },
  {
    "id": 92,
    "subject": "https://petkeen.com/can-a-horse-vomit/#:~:text=Horses%20cannot%20throw%20up%20because,it%20possible%20to%20throw%20up.",
    "claim": "rated",
    "object": "Horses can't vomit.",
    "qualifier": "Horses cannot throw up because their body is not designed so that food can go the opposite direction. Their food can only go down, not up. For example, horses have muscles that make it absolutely impossible to open the valve that makes it possible to throw up",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://petkeen.com/",
    "effectiveDate": "2022-07-01T14:10:58.502Z",
    "confidence": 0.7,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T14:13:18.437Z",
    "lastUpdatedAt": "2022-07-01T14:13:18.437Z"
  },
  {
    "id": 94,
    "subject": "https://www.penguin.co.uk/books/396024/the-book-thief-by-zusak-markus/9781909531611",
    "claim": "rated",
    "object": null,
    "qualifier": null,
    "aspect": "quality:literary",
    "howKnown": "first_hand",
    "source": null,
    "effectiveDate": "2022-07-01T20:48:45.430Z",
    "confidence": 1,
    "reviewRating": 4,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T20:49:49.937Z",
    "lastUpdatedAt": "2022-07-01T20:49:49.937Z"
  },
  {
    "id": 64,
    "subject": "https://www.nationsonline.org/oneworld/african_languages.htm#:~:text=Africa%20is%20a%20continent%20with,estimated%201500%2D2000%20African%20languages.&text=gathering%20appoximately%20140%20languages%20with,in%20Central%20and%20Eastern%20Africa.",
    "claim": "rated",
    "object": " There are over 2000 different languages spoken in Africa",
    "qualifier": "Africa is a continent with a very high linguistic diversity, there are an estimated 1500-2000 African languages. gathering appoximately 140 languages with some eleven millions speakers scattered in Central and Eastern Africa.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nationsonline.or",
    "effectiveDate": "2022-07-01T09:49:18.082Z",
    "confidence": 0.83,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T09:53:53.054Z",
    "lastUpdatedAt": "2022-07-01T09:53:53.054Z"
  },
  {
    "id": 70,
    "subject": "https://www.statista.com/statistics/505883/number-of-internet-users-in-african-countries/",
    "claim": "rated",
    "object": "MORE PEOPLE IN NEW YORK CITY HAVE INTERNET ACCESS THAN THE WHOLE CONTINENT OF AFRICA",
    "qualifier": "As you may expect, Africa is very behind the “digital divide” and there are more people in the one single city of New York with internet access than the entire continent and the 54 countries of Africa!",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://en.wikipedia.org/wiki/Internet_in_Africa",
    "effectiveDate": "2022-07-01T10:19:31.638Z",
    "confidence": 0.69,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:22:25.779Z",
    "lastUpdatedAt": "2022-07-01T10:22:25.779Z"
  },
  {
    "id": 79,
    "subject": "https://www.livescience.com/15322-healthiest-backyard-weeds.html",
    "claim": "rated",
    "object": "Weeds can be healthy.",
    "qualifier": "Though we usually just pull them up and toss them into the trash, some weeds have nutritious properties. For example, dandelions are loaded with vitamins A, C, and K—not to mention calcium, iron, and potassium. So consider repurposing those weeds and making them into a salad.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.livescience.com/",
    "effectiveDate": "2022-07-01T10:50:42.855Z",
    "confidence": 0.61,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T10:53:11.804Z",
    "lastUpdatedAt": "2022-07-01T10:53:11.804Z"
  },
  {
    "id": 83,
    "subject": "https://climate.nasa.gov/news/2540/tree-rings-provide-snapshots-of-earths-past-climate/",
    "claim": "rated",
    "object": "Tree rings get wider during wet years.",
    "qualifier": "You probably already know that tree rings can tell you how old a tree is. But they can also show you the conditions of a given year, according to NASA: Thinner rings appear during drought years, and thick ones mean there was significant rainfall.",
    "aspect": "impact:educational",
    "howKnown": "website",
    "source": "https://www.nasa.gov/",
    "effectiveDate": "2022-07-01T11:04:35.832Z",
    "confidence": 0.77,
    "reviewRating": 5,
    "userId": 5,
    "issuerId": "http://trustclaims.whatscookin.us/users/5",
    "issuerIdType": "URL",
    "createdAt": "2022-07-01T11:07:08.562Z",
    "lastUpdatedAt": "2022-07-01T11:07:08.562Z"
  },
  {
    "id": 95,
    "subject": "My Claim",
    "claim": "same_as",
    "object": null,
    "qualifier": null,
    "aspect": "quality:relevance",
    "howKnown": "second_hand",
    "source": null,
    "effectiveDate": "2022-07-07T20:42:09.900Z",
    "confidence": 0.2,
    "reviewRating": null,
    "userId": 11,
    "issuerId": "http://trustclaims.whatscookin.us/users/11",
    "issuerIdType": "URL",
    "createdAt": "2022-07-07T20:42:28.973Z",
    "lastUpdatedAt": "2022-07-07T20:42:28.973Z"
  },
  {
    "id": 97,
    "subject": "https://github.com/pacodes",
    "claim": "rated",
    "object": null,
    "qualifier": "88 stars on github",
    "aspect": "impact:work",
    "howKnown": null,
    "source": "https://github.com/pacodes",
    "effectiveDate": "2022-07-13T08:24:28.975Z",
    "confidence": null,
    "reviewRating": 5,
    "userId": 3,
    "issuerId": "http://trustclaims.whatscookin.us/users/3",
    "issuerIdType": "URL",
    "createdAt": "2022-07-13T08:28:07.928Z",
    "lastUpdatedAt": "2022-07-13T08:28:07.928Z"
  }
]
