export default [
  {
    id: 9914,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/VEJA",
    statement:
      "The VEJA project creates a positive chain. Sneakers are made differently using organic, agroecological and fairtrade cotton to make the sneakers canvas, wild rubber from the Amazonian Forest for its soles and innovative materials such as recycled plastic bottles to create a new mesh. VEJA is about minimalism and innovation. Their logistics and shipping run by Ateliers Sans Frontières, a rehabilitation association. Made in Brazil.",
    aspect: "social:impact",
    howKnown: null,
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T13:53:28.457",
    lastUpdatedAt: "2022-08-17T13:53:28.457",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9915,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Maanch",
    statement:
      "Maanch is an award winning global impact platform, transforming the way millions of people engage with philanthropy and impact investing worldwide. \\r\\n\\r\\nMaanch aims to influence the flow of funds towards global sustainable development, by providing technology, data and insights on social, environmental, and economic impact.\\r\\n\\r\\nMaanch provides tailor made digital solutions for individuals & families, private banks , wealth advisory firms, grant making trusts and foundations, CSR teams, UK registered charities and international nonprofit organisations .",
    aspect: "social:impact",
    howKnown: null,
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T13:53:28.457",
    lastUpdatedAt: "2022-08-17T13:53:28.457",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9916,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Olli%20Ella",
    statement:
      "Olli Ella creates timeless pieces that continue to be loved through the generations with emphasis on diversity and social inclusion.  Focused on natural and mindfully sourced materials with true attention on craftsmanship and uplifting the communities where they are made. \\r\\n\\r\\nFounded in 2010 by sisters, Chloe & Olivia Brookman, the company now stretches across the globe with offices in Australia, United Kingdom, USA and Netherlands. Lead with a social and environmental compass, Olli Ella continues to uphold their commitment to use business as a force for good, whilst still evoking a sense of play, fun, quirk and adventure.",
    aspect: "social:impact",
    howKnown: null,
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T13:53:28.457",
    lastUpdatedAt: "2022-08-17T13:53:28.457",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9917,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Luxelare",
    statement:
      "Luxelare is an agro-tech/insurtech company, offering small to medium sized farmers an integrated solution combing precision agriculture and the CAPTUM software platform and digital crop insurance products.",
    aspect: "social:impact",
    howKnown: null,
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T13:53:28.457",
    lastUpdatedAt: "2022-08-17T13:53:28.457",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9921,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/VEJA",
    statement:
      "The VEJA project creates a positive chain. Sneakers are made differently using organic, agroecological and fairtrade cotton to make the sneakers canvas, wild rubber from the Amazonian Forest for its soles and innovative materials such as recycled plastic bottles to create a new mesh. VEJA is about minimalism and innovation. Their logistics and shipping run by Ateliers Sans Frontières, a rehabilitation association. Made in Brazil.",
    aspect: "social:impact",
    howKnown: "first_hand",
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T14:08:41.826",
    lastUpdatedAt: "2022-08-17T14:08:41.826",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9922,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Maanch",
    statement:
      "Maanch is an award winning global impact platform, transforming the way millions of people engage with philanthropy and impact investing worldwide. \\r\\n\\r\\nMaanch aims to influence the flow of funds towards global sustainable development, by providing technology, data and insights on social, environmental, and economic impact.\\r\\n\\r\\nMaanch provides tailor made digital solutions for individuals & families, private banks , wealth advisory firms, grant making trusts and foundations, CSR teams, UK registered charities and international nonprofit organisations .",
    aspect: "social:impact",
    howKnown: "first_hand",
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T14:08:41.826",
    lastUpdatedAt: "2022-08-17T14:08:41.826",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9923,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Olli%20Ella",
    statement:
      "Olli Ella creates timeless pieces that continue to be loved through the generations with emphasis on diversity and social inclusion.  Focused on natural and mindfully sourced materials with true attention on craftsmanship and uplifting the communities where they are made. \\r\\n\\r\\nFounded in 2010 by sisters, Chloe & Olivia Brookman, the company now stretches across the globe with offices in Australia, United Kingdom, USA and Netherlands. Lead with a social and environmental compass, Olli Ella continues to uphold their commitment to use business as a force for good, whilst still evoking a sense of play, fun, quirk and adventure.",
    aspect: "social:impact",
    howKnown: "first_hand",
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T14:08:41.826",
    lastUpdatedAt: "2022-08-17T14:08:41.826",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
  {
    id: 9924,
    subject: "https://www.bcorporation.net/",
    claim: "rated",
    object: "http://trustclaims.whatscookin.us/local/company/Luxelare",
    statement:
      "Luxelare is an agro-tech/insurtech company, offering small to medium sized farmers an integrated solution combing precision agriculture and the CAPTUM software platform and digital crop insurance products.",
    aspect: "social:impact",
    howKnown: "first_hand",
    sourceURI: "https://data.world/blab/b-corp-impact-data",
    effectiveDate: null,
    confidence: 0.8,
    stars: 5,
    userId: 2,
    createdAt: "2022-08-17T14:08:41.826",
    lastUpdatedAt: "2022-08-17T14:08:41.826",
    issuerId: "http://trustclaims.whatscookin.us/users/2",
    issuerIdType: "URL",
  },
];
