const BACKEND_BASE_URL = import.meta.env.VITE_BACKEND_BASE_URL
const GITHUB_CLIENT_ID = import.meta.env.VITE_GITHUB_CLIENT_ID
const CERAMIC_URL = import.meta.env.VITE_CERAMIC_URL
const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID
const GOOGLE_REDIRECT_URI = import.meta.env.VITE_GOOGLE_REDIRECT_URI

export { BACKEND_BASE_URL, GITHUB_CLIENT_ID, CERAMIC_URL, GOOGLE_CLIENT_ID, GOOGLE_REDIRECT_URI }
