const BACKEND_BASE_URL = import.meta.env.VITE_BACKEND_BASE_URL
const GITHUB_CLIENT_ID = import.meta.env.VITE_GITHUB_CLIENT_ID
const CERAMIC_URL = import.meta.env.VITE_CERAMIC_URL
const LINKEDIN_CLIENT_ID = import.meta.env.VITE_LINKEDIN_CLIENT_ID
const LINKEDIN_REDIRECT_URI = import.meta.env.VITE_LINKEDIN_REDIRECT_URI
const LINKEDIN_SCOPE = import.meta.env.VITE_LINKEDIN_SCOPE

export { BACKEND_BASE_URL, GITHUB_CLIENT_ID, CERAMIC_URL, LINKEDIN_CLIENT_ID, LINKEDIN_REDIRECT_URI, LINKEDIN_SCOPE }
