const BACKEND_BASE_URL = import.meta.env.VITE_BACKEND_BASE_URL
const CERAMIC_URL = import.meta.env.VITE_CERAMIC_URL
const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID

export { BACKEND_BASE_URL, CERAMIC_URL, GOOGLE_CLIENT_ID }
