on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linter
    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: install
        run: npm i

      - name: Run JS linter
        run: npm run lint

      - name: build
        run: npm run build
